
#@TYPE: Machine
#@NAME: Falcon-S1 Lite
#@DESCRIPTION: Falcon-s1-lite variant  (Single ethernet, no PCIe)

# Pull in shared 8GB RAM, WiFi, and Systemd logic
require conf/machine/include/falcon-s1-common.inc

# Specific Override for Lite-only patches
MACHINEOVERRIDES =. "falcon-s1-lite:"

# Binary Targets (Kernel)
KERNEL_DEVICETREE = "freescale/falcon-s1-lite.dtb"

# U-Boot Targets
# we are using evk_defconfig 
# because we haven't created a custom U-Boot source yet.
UBOOT_CONFIG[sd] = "imx8mp_evk_defconfig,sdcard"
UBOOT_DTB_NAME = "imx8mp-evk.dtb"

# Remove the PCI feature 
MACHINE_FEATURES:remove = "pci"
