#@TYPE: Machine
#@NAME: Falcon-S1 
#@DESCRIPTION: Falcon-S1 full variant without hailo 

# Pull in shared logic
require conf/machine/include/falcon-s1-common.inc

# Specific Override
MACHINEOVERRIDES =. "falcon-s1:"

# Binary Targets
KERNEL_DEVICETREE = "freescale/falcon-s1.dtb"

# U-Boot Targets: 
# we are using evk_defconfig 
# because we haven't created a custom U-Boot source yet.
UBOOT_CONFIG[sd] = "imx8mp_evk_defconfig,sdcard"
UBOOT_DTB_NAME = "imx8mp-evk.dtb"

# 5. Multimedia/AI Support
# This tells the image to include the Hailo drivers and NPU firmware
#MACHINE_EXTRA_RRECOMMENDS += "i2c-tools gpiod"
