#@TYPE: Machine
#@NAME: Falcon-S1-Hailo
#@DESCRIPTION: Falcon-S1 hailo variant (Hailo-8 M.2)

# Pull in shared logic
require conf/machine/include/falcon-s1-common.inc

# Specific Override
MACHINEOVERRIDES =. "falcon-s1-hailo:"

# Binary Targets
KERNEL_DEVICETREE = "freescale/falcon-s1-hailo.dtb"

# U-Boot Targets
# we are using evk_defconfig 
# because we haven't created a custom U-Boot source yet.
UBOOT_CONFIG[sd] = "imx8mp_evk_defconfig,sdcard"
UBOOT_DTB_NAME = "imx8mp-evk.dtb"

# Hailo Stack
# This automatically adds the drivers/firmware to any image (Minimal/Full)
# MACHINE_EXTRA_RRECOMMENDS += "hailo-firmware hailo-pci-driver"