#  Path Setup: Tell BitBake where to find recipes
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

#  Layer Identity
BBFILE_COLLECTIONS += "meta-falcon-s1"
BBFILE_PATTERN_meta-falcon-s1 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-falcon-s1 = "10"

#  Define Yocto version compatibility
# Supports Kirkstone (Long Term Support) and newer versions
LAYERSERIES_COMPAT_meta-falcon-s1 = "kirkstone mickledore scarthgap"

#  Dependencies: Ensure NXP base layers are present
LAYERDEPENDS_meta-falcon-s1 = "core fsl-bsp-release"
