ctrl_interface=/var/run/wpa_supplicant
ap_scan=1
network={
    ssid="nothing"
    psk="12345678"
    key_mgmt=WPA-PSK
}
network={
    ssid="Pixel_7899"
    psk="123456789"
    key_mgmt=WPA-PSK
}
network={
    ssid="QuestAdaptations"
    psk="Quest0124556044"
    key_mgmt=WPA-PSK
    priority=1
}   
